import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "../styles/Home.module.css";
import { useRouter } from "next/router";

import React, { useState, useEffect } from "react";
import axios from "axios";

import style from "../Components/LandingPage/Hero.module.css";
import Footer from "../Components/Footer/Footer";
import Form from "../Components/Form/Form";
import Zoom from "react-medium-image-zoom";
import "react-medium-image-zoom/dist/styles.css";

const Home = () => {
	// form config

	var imageSize = {
		width: "300px",
		height: "400px",
	};

	const [students, setStudents] = useState([]);
	const router = useRouter();

	const { id } = router.query;

	const myFunction = async () => {
		const res = await axios.get(`https://fejs-c7-api.herokuapp.com/api/students/?populate=*`);
		setStudents([...res.data.data]);
	};

	useEffect(() => {
		myFunction();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Form />
				<div className={style.card_container}>
					{students.map((student) => {
						return (
							<div key={student.id} className={`card ` + style.card_}>
								<div className={style.img_container}>
									{student.attributes.photo.data !== null && (
										<Zoom>
											<img className="card-img-top img-thumbnail" src={student.attributes.photo.data.attributes.url} style={imageSize} />
										</Zoom>
									)}
									<div className={`card-body` + style.cardBody}>
										<p className="card-text">First Name: {student.attributes.firstname}</p>
										<p className="card-text">Last Name: {student.attributes.lastname}</p>
										<p className="card-text">Location: {student.attributes.location}</p>
									</div>
								</div>
							</div>
						);
					})}
				</div>

				<div className={`${style.bg_footer} mt-5`}>
					<Footer />
				</div>
			</main>
		</div>
	);
};
export default Home;